const GET_COUNTRIES = 'GET_COUNTRIES';
const FILTER_ALPHABETICALLY = 'FILTER_ALPHABETICALLY';
const FILTER_UNALPHABETICALLY = 'FILTER_UNALPHABETICALLY';
const FILTER_DECREASING_POPULATION = 'FILTER_DECREASING_POPULATION';
const FILTER_INCREASING_POPULATION = 'FILTER_INCREASING_POPULATION';
const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
const SEARCH = 'SEARCH';
const DETAIL = 'DETAIL';
const GET_ACTIVITIES = 'GET_ACTIVITIES';


export {
    GET_COUNTRIES,
    FILTER_ALPHABETICALLY,
    FILTER_UNALPHABETICALLY,
    FILTER_DECREASING_POPULATION,
    FILTER_INCREASING_POPULATION,
    FILTER_BY_CONTINENT,
    SEARCH,
    DETAIL,
    GET_ACTIVITIES
};